
<h4><span>Portal</span> demo login</h4>
<ul class="links">
    <?=$this->action('index', 'demo', 'default');?>
</ul>
<!--
<h4><span>Blandit</span> Consequat</h4>
<ul class="links">
<li class="first"><a href="#">Dui neque fringilla</a></li>
    <li><a href="#">Metus sed donec</a></li>
    <li><a href="#">Semper nisi molestie</a></li>
    <li><a href="#">Sed cursus</a></li>
    <li><a href="#">Tempus nullam</a></li>
    <li><a href="#">Semper nisi molestie</a></li>
    <li><a href="#">Sed bibendum mauris</a></li>
</ul>

<h4><span>Cool</span> Stuff</h4>
<ul class="links">
    <li class="first"><a href="http://www.nodethirtythree.com/">NodeThirtyThree</a></li>
    <li><a href="http://www.4templates.com/?aff=n33">4Templates.com</a></li>
    <li><a href="http://www.wpthemepark.com/">WPThemePark</a></li>
    <li><a href="http://www.openwebdesign.org/userinfo.phtml?user=node33">OpenWebDesign</a></li>
    <li><a href="http://www.zeroweb.org/">Zeroweb.org</a></li>
</ul>-->
