<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--

	Nonzero1.0 by nodethirtythree design
	http://www.nodethirtythree.com
	missing in a maze

-->
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=iso-8859-1" />
    <?= $this->headTitle() ?>
    <?= $this->headScript() ?>
    <link rel="stylesheet" type="text/css" href="/nonzero/nonzero_actual/nonzero_red/style.css" />
    <?= $this->headStyle() ?>
</head>
<body>

<div id="header">

	<div id="header_inner" class="fluid">

		<div id="logo">
			<h1><span>SoftLayer API Portal</span></h1>
		</div>
		
		<div id="menu">
            <?=$this->action('menu', 'navigation', 'default');?>
		</div>
		
	</div>
</div>

<div id="main">

	<div id="main_inner" class="fluid">

		<div id="primaryContent_2columns">

			<div id="columnA_2columns">
	            <?=$this->layout()->content?>	
			</div>
	
		</div>
		
		<div id="secondaryContent_2columns">
			<div id="columnC_2columns">
                <?=$this->action('sidebar', 'navigation', 'default');?>
			</div>
		</div>

		<br class="clear" />

	</div>

</div>

<div id="footer" class="fluid">
	Design by <a href="http://www.nodethirtythree.com/">NodeThirtyThree Design</a>.
</div>

</body>
</html>
